### ISSUE TITLE
Support for npm exec?

### ISSUE THREAD

**Issue by basickarl** [dkundel/node-env-run#26]
Yo! I don't have `vue-cli-service` installed globally (cannot be found by my shell) and will not install it globally (hence why I use `npm exec`), so wondering how I would get this working?
```
> npm exec -- nodenv --env configs/.env.development --exec 'npm exec -- vue-cli-service serve'

Error: Failed to determine script to execute
    at Object.init (D:\Development\langurama\web\node_modules\node-env-run\dist\lib\cli.js:89:23)
    at Object.<anonymous> (D:\Development\langurama\web\node_modules\node-env-run\dist\bin\node-env-run.js:29:19)    
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

The command per say works when manually using it, but when I use it in a package.json script it doesn't :/.

 `"development": "npm exec -- nodenv --env configs/.env.development --exec 'npm exec -- vue-cli-service serve'",`

**Comment by basickarl** [comment]
Fixed it: `"development": "npm exec -- nodenv --env configs/.env.development --exec npm -- exec -- vue-cli-service serve",`
